name: humm
description: Humm cli package
version: 1.0.1+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: 2.6.0
  cli_completion: 0.5.0
  mason_logger: 0.2.5
  pub_updater: 0.5.0
  http: 1.2.2
  io: 1.0.3
  path: 1.8.2

dev_dependencies:
  build_runner: 2.4.9
  build_verify: 3.1.0
  build_version: 2.1.1
  mocktail: 1.0.0
  test: 1.25.14
  very_good_analysis: 7.0.0
  mockito: 5.4.4



executables:
  humm:
